server:
  port: 8081
logging:
  level.root: info


spring:
  datasource:
    username: root
    password: cloudalibaba
    url: jdbc:mysql://zmz121.cn:3306/shareway?useSSL=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: zmz121.cn
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
    password: cloudalibaba
  cloud:
    nacos:
      discovery:
        server-addr: zmz121.cn:8848
        namespace: f678b632-7899-4a2d-acd7-8c7c3394b573

dubbo:
  # 配置服务信息
  application:
    name: dubbo-consumer
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://zmz121.cn:8848
  # 设置超时时间
  consumer:
    timeout: 4000



token:
  secret: nwafu
  # 单位 分钟
  expiration: 30





mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml